//! Side-query traits attached to visages.
//!
//! `HerdSummary` is the visage struct generated by `#[field(expose(
//! summary))]` on `Herd` — it lives at `crate::models::HerdSummary`
//! after the `#[model]` macro expands. This module attaches an extra
//! `herd_size` method through a trait so the count is opt-in rather
//! than denormalised onto every row.

pub mod herd_summary;

pub use herd_summary::{HerdSizeQuery, HerdSummary};
