// Cluster 8δ T7.5 — macro-emitted `save` / `delete` on_commit hooks compile
// for a `pk = RanjId` (UUIDv8) model.
//
// Extends the HeerId fixture (`phase8_t7_5_save_emits_on_commit.rs`) by
// verifying that the `__id_for_cache: <PK>` capture inside the `on_commit`
// closure is `Send + 'static` for non-HeerId primary keys.
//
// Specifically pins:
//   - The macro-emitted `on_commit` closure captures `__id_for_cache: RanjId`
//     (a `uuid::Uuid` newtype) — which is `Clone + Send + Sync + 'static` — so
//     the async block satisfies the `Send + 'static` bound required by the
//     `on_commit` substrate.
//   - `InvalidationReason` re-export path is `::djogi::cache::InvalidationReason`
//     (not `::sassi::*`).
//   - The `Cacheable` impl generated by `#[derive(Model)]` for a RanjId model
//     compiles cleanly (associating `Cacheable::Id = RanjId`).
//
// If any path in the emitted hook block is wrong (wrong PK type parameter,
// wrong Cacheable::Id association, missing trait bounds), this fixture fails
// to compile — catching the error before the integration suite runs.
//
// Path-routing contract (per `feedback_macro_path_routing.md`):
//   - `::djogi::cache::InvalidationReason::OnSave`  — save path
//   - `::djogi::cache::InvalidationReason::OnDelete` — delete path
//
// Every lihaaf compile-fixture must
// have `fn main` so the stored binary can link.
//
// Spec anchor:
//   docs/superpowers/plans/granular-phase8/cluster-8delta-granular.md
//   §3 commit T7.5 — compile-pass fixture bullet (the plan calls it
//   "Trybuild compile-pass fixture"; this fixture is now run through
//   lihaaf).

use djogi::prelude::*;

#[model(table = "phase8_t7_5_on_commit_ranjid_rows", pk = RanjId)]
#[derive(Debug, Clone)]
pub struct OnCommitRanjRow {
    pub label: String,
}

// Witness that `InvalidationReason` is reachable through `djogi::cache`
// (the path the macro-emitted code spells), and that the model has a
// `Cacheable` impl with the correct `Id = RanjId` association.
fn _accept_invalidation_reason(
    _: ::djogi::cache::InvalidationReason,
) {
}

fn _accept_cacheable_id(_: <OnCommitRanjRow as ::djogi::cache::Cacheable>::Id) {
}

fn main() {
    _accept_invalidation_reason(::djogi::cache::InvalidationReason::OnSave);
    _accept_invalidation_reason(::djogi::cache::InvalidationReason::OnDelete);
    // Verify the Cacheable::Id is RanjId — if the macro emits the wrong
    // PK type in the `Cacheable` impl, the call below will fail to compile
    // because `RanjId` and the actual `Cacheable::Id` would be incompatible.
    // `RanjId::ZERO` is the canonical in-memory placeholder (nil UUID).
    _accept_cacheable_id(::djogi::types::RanjId::ZERO);
}
