//! DDL audit ledger — append-only record of every migration applied to
//! the application database, written to the `crud_log_url` audit DB so
//! that `djogi db reset` (which targets only the app DB) cannot erase
//! the audit trail.
//!
//! # Three-database awareness (CLAUDE.md "Three-Database Architecture")
//!
//! Djogi maintains three separate connection pools at runtime — `url`
//! (application data), `crud_log_url` (per-model `_logs` mirrors AND
//! the migration audit ledger), and `event_log_url` (request /
//! crash / debug events). The audit DB is intentionally a different
//! Postgres database from the app DB so `djogi db reset` (which drops
//! and recreates the app DB) leaves the audit trail intact. T9.5
//! wires `record_ddl` into the apply path; T9.6 surfaces the audit
//! rows through `djogi verify`.
//!
//! # Schema
//!
//! ```sql
//! CREATE TABLE IF NOT EXISTS djogi_ddl_audit (
//!     id                       BIGSERIAL    PRIMARY KEY,
//!     applied_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
//!     target_database          TEXT         NOT NULL,
//!     app_label                TEXT         NOT NULL,
//!     ddl_sql                  TEXT         NOT NULL,
//!     snapshot_signature_hex   TEXT
//! );
//! ```
//!
//! # Why `BIGSERIAL`, not `BIGINT DEFAULT heerid_next()`
//!
//! 1. The audit DB may not have HeeRanjId's `heerid_next()` extension
//!    installed — the audit DB is operationally separate and we do
//!    not want to require the operator to install a sibling extension
//!    in two databases.
//! 2. `BIGSERIAL` is appropriate for a pure-append table where
//!    monotonic time-ordering matters but cross-shard uniqueness
//!    does not — the audit DB is single-writer (only the migration
//!    runner writes to it).
//! 3. `BIGSERIAL` (i.e. `BIGINT GENERATED BY DEFAULT AS IDENTITY` is
//!    the modern equivalent — Postgres still accepts the SERIAL
//!    pseudo-types and emits the identity column under the hood).
//!
//! # Wiring status (Cluster 8ε)
//!
//! - **T9.4 (this commit)** — schema bootstrap + write helpers +
//!   `RunnerCtx::audit_pool` field. NOT yet called from the apply
//!   path.
//! - **T9.5** — wires `record_ddl` into `apply_plan_inner` so every
//!   successful migration writes an audit row.
//! - **T9.6** — `djogi verify` CLI surface that reads from this
//!   table.
//!
//! # Spec / memory anchors
//!
//! - v3 plan §453 (audit table schema), §469 (T9 cluster boundary).
//! - CLAUDE.md "Three-Database Architecture".

use crate::__bypass::RawAccessExt as _;
use crate::context::DjogiContext;
use crate::error::DjogiError;

/// SQL DDL for the `djogi_ddl_audit` table. Public so tests and any
/// future `init`-style command can replay it without going through
/// [`bootstrap_ddl_audit`].
///
/// The DDL uses `IF NOT EXISTS` so calling [`bootstrap_ddl_audit`]
/// on every runner invocation is a no-op after the first.
pub const DDL_AUDIT_TABLE_DDL: &str = r#"
CREATE TABLE IF NOT EXISTS djogi_ddl_audit (
    id                       BIGSERIAL    PRIMARY KEY,
    applied_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    target_database          TEXT         NOT NULL,
    app_label                TEXT         NOT NULL,
    ddl_sql                  TEXT         NOT NULL,
    snapshot_signature_hex   TEXT
);
"#;

/// Idempotently create the `djogi_ddl_audit` table in the audit DB.
///
/// The caller MUST supply a context whose pool points at the audit
/// DB (i.e. `crud_log_url`), not the application DB. This invariant
/// is operational, not type-enforced — `DjogiContext` is single-pool
/// today, so the safety hinges on the runner constructing the
/// audit-side context from `RunnerCtx::audit_pool` rather than the
/// app-side pool.
///
/// Routes through `DjogiContext::raw_ddl` (Postgres simple-query
/// protocol) because `CREATE TABLE` does not benefit from server-side
/// prepare and some of its features (notably `IF NOT EXISTS` against
/// shared catalogs) historically misbehaved on the prepared path.
pub async fn bootstrap_ddl_audit(audit_ctx: &mut DjogiContext) -> Result<(), DjogiError> {
    audit_ctx.raw_ddl(DDL_AUDIT_TABLE_DDL).await
}

/// Append one DDL audit row. Returns the generated `id`.
///
/// # Parameters
///
/// - `target_database` — the application database the migration ran
///   against (e.g. `"main"`, `"analytics"`). This is the bucket's
///   `database` field; the audit DB stores rows from every target
///   in one table so an operator can query the global migration
///   history with a single `SELECT`.
/// - `app_label` — the bucket's `app` field (empty string for the
///   synthetic global bucket).
/// - `ddl_sql` — the concatenated SQL that ran for this migration.
///   The runner records the full statement text, not a hash; the
///   audit DB is operationally separate and recovery scenarios may
///   need the original SQL even if the migrations submodule is
///   unreachable.
/// - `snapshot_sig_hex` — `Some(64-byte hex string)` when the
///   signing key is configured (HMAC-SHA256 of the persisted
///   snapshot); `None` for the no-op default.
///
/// # Why parameterised binds, not `format!`
///
/// `ddl_sql` carries the unredacted operator-supplied SQL — passing
/// it through `format!` would create a literal SQL-injection vector
/// inside the audit logger itself. Every value goes through
/// `tokio_postgres`' positional bind path; no string interpolation
/// occurs in this function.
pub async fn record_ddl(
    audit_ctx: &mut DjogiContext,
    target_database: &str,
    app_label: &str,
    ddl_sql: &str,
    snapshot_sig_hex: Option<&str>,
) -> Result<i64, DjogiError> {
    let sql = "INSERT INTO djogi_ddl_audit \
               (target_database, app_label, ddl_sql, snapshot_signature_hex) \
               VALUES ($1, $2, $3, $4) \
               RETURNING id";
    let row = audit_ctx
        .query_one(
            sql,
            &[&target_database, &app_label, &ddl_sql, &snapshot_sig_hex],
        )
        .await?;
    Ok(row.try_get::<_, i64>(0)?)
}

/// Encode a 32-byte HMAC-SHA256 signature as a 64-character UPPERCASE
/// hex string.
///
/// The output matches `format!("{:02X}", byte)` for each input byte,
/// concatenated. We pick uppercase to match the `crud_log` column
/// convention in `djogi_schema_migrations` siblings (the ledger
/// `checksum_up` is lowercase by historical accident; new audit
/// surfaces ship uppercase to make the two visually distinguishable
/// in operator logs).
///
/// # Why a hand-rolled encoder
///
/// Djogi prohibits adding regex, base16, hex, or similar single-purpose
/// crates when 16 lines of stdlib do the job. Allocates exactly one
/// 64-byte `String`; no intermediate `Vec`, no per-byte `format!`
/// allocation.
pub fn signature_to_hex(sig: &[u8; 32]) -> String {
    const HEX: &[u8; 16] = b"0123456789ABCDEF";
    let mut out = String::with_capacity(64);
    for &byte in sig {
        out.push(HEX[(byte >> 4) as usize] as char);
        out.push(HEX[(byte & 0x0F) as usize] as char);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── signature_to_hex — pure unit tests, no DB needed ────────────

    #[test]
    fn signature_to_hex_all_zero() {
        // 32 zero bytes → 64 ASCII '0' characters.
        let sig = [0u8; 32];
        let hex = signature_to_hex(&sig);
        assert_eq!(hex, "0".repeat(64));
        assert_eq!(hex.len(), 64);
    }

    #[test]
    fn signature_to_hex_all_ones() {
        // 32 0xFF bytes → 64 'F's (uppercase).
        let sig = [0xFFu8; 32];
        let hex = signature_to_hex(&sig);
        assert_eq!(hex, "F".repeat(64));
    }

    #[test]
    fn signature_to_hex_known_mixed_bytes() {
        // Cross-check against `format!("{:02X}", b)` for a mixed
        // byte pattern. If `signature_to_hex` ever drifts from the
        // canonical uppercase encoding (e.g. nibble-swap, lowercase
        // typo, off-by-one in the lookup table), this test trips.
        let mut sig = [0u8; 32];
        // Pattern: byte i = (i * 17 + 3) mod 256. Hits low-nibble,
        // high-nibble, and crossover (a..f) cases.
        for (i, byte) in sig.iter_mut().enumerate() {
            *byte = ((i as u32 * 17 + 3) & 0xFF) as u8;
        }

        let actual = signature_to_hex(&sig);
        let expected: String = sig.iter().map(|b| format!("{b:02X}")).collect();
        assert_eq!(actual, expected);
        assert_eq!(actual.len(), 64);
        // Every byte must be ASCII hex uppercase.
        assert!(
            actual
                .bytes()
                .all(|b| matches!(b, b'0'..=b'9' | b'A'..=b'F')),
            "non-uppercase-hex byte in {actual:?}"
        );
    }

    // ── DB-dependent tests — same-pool audit fixture ─────────────────────

    use djogi_macros::djogi_test;

    #[djogi_test]
    async fn bootstrap_is_idempotent(mut ctx: DjogiContext) {
        bootstrap_ddl_audit(&mut ctx)
            .await
            .expect("first bootstrap_ddl_audit");
        bootstrap_ddl_audit(&mut ctx)
            .await
            .expect("second bootstrap_ddl_audit");

        let count: i64 = ctx
            .query_one("SELECT COUNT(*)::bigint FROM djogi_ddl_audit", &[])
            .await
            .expect("count djogi_ddl_audit")
            .try_get(0)
            .expect("decode count");
        assert_eq!(count, 0, "bootstrap should create the table but no rows");
    }

    #[djogi_test]
    async fn record_ddl_returns_increasing_ids(mut ctx: DjogiContext) {
        bootstrap_ddl_audit(&mut ctx)
            .await
            .expect("bootstrap audit");

        let a = record_ddl(
            &mut ctx,
            "main",
            "",
            "CREATE TABLE audit_a (id bigint)",
            Some("AA"),
        )
        .await
        .expect("record first ddl");
        let b = record_ddl(
            &mut ctx,
            "main",
            "",
            "CREATE TABLE audit_b (id bigint)",
            Some("BB"),
        )
        .await
        .expect("record second ddl");
        let c = record_ddl(
            &mut ctx,
            "main",
            "",
            "CREATE TABLE audit_c (id bigint)",
            Some("CC"),
        )
        .await
        .expect("record third ddl");

        assert!(a < b && b < c, "audit ids should increase: {a}, {b}, {c}");
    }

    #[djogi_test]
    async fn record_ddl_accepts_null_signature(mut ctx: DjogiContext) {
        bootstrap_ddl_audit(&mut ctx)
            .await
            .expect("bootstrap audit");

        let id = record_ddl(
            &mut ctx,
            "main",
            "",
            "CREATE TABLE audit_null_signature (id bigint)",
            None,
        )
        .await
        .expect("record ddl with null signature");
        let sig: Option<String> = ctx
            .query_one(
                "SELECT snapshot_signature_hex FROM djogi_ddl_audit WHERE id = $1",
                &[&id],
            )
            .await
            .expect("select audit row")
            .try_get(0)
            .expect("decode signature");
        assert_eq!(sig, None);
    }
}
