//! Projection runtime — error types for Phase 4.5 generated projection structs.
//!
//! Phase 4.5 emits four projection structs per `#[model]` struct
//! (`{Model}Public`, `{Model}SelfView`, `{Model}Admin`, `{Model}Export`) plus
//! conversion impls. This module holds the runtime-side types those
//! conversions depend on:
//!
//! - [`ProjectionError`] — the fallible-conversion error type, returned by
//!   every `TryFrom<&Model>` impl that nests a relation-form peer projection.
//!   `#[non_exhaustive]` so later phases (e.g. protected-data in Phase 7.5)
//!   can add variants without a breaking change.
//! - `impl From<Infallible> for ProjectionError` — unreachable glue that lets
//!   generated code propagate `Infallible` with `?` when a peer projection is
//!   scalar-only.
//!
//! No runtime execution happens here — every path is straight-line error
//! construction or formatting.

use std::convert::Infallible;

/// Error returned by a fallible projection conversion (`TryFrom<&Model>`).
///
/// Generated by Phase 4.5 codegen whenever a projection nests at least one
/// peer projection via a relation field. The only variant today is
/// [`ProjectionError::UnresolvedRelation`], raised when the caller forgot to
/// `prefetch` / `select_related` the relation before projecting.
///
/// `#[non_exhaustive]` is intentional: Phase 7.5 protected-data governance
/// and later phases may add variants (e.g. redaction failures, codec errors)
/// without breaking the public API.
#[non_exhaustive]
#[derive(Debug)]
pub enum ProjectionError {
    /// A relation field was projected before the relation was loaded.
    ///
    /// Fix: call `.prefetch(|r| r.<field>())` (or `.select_related(...)` for
    /// SQL-JOIN eager loading) on the queryset before invoking
    /// `TryFrom::try_from(&model)`.
    UnresolvedRelation {
        /// Name of the owning model (`struct` ident).
        model: &'static str,
        /// Name of the relation field on the owning model.
        field: &'static str,
        /// Projection scope whose `TryFrom` impl raised this error
        /// (`public` / `self_view` / `admin` / `export`).
        scope: &'static str,
    },
}

impl std::fmt::Display for ProjectionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProjectionError::UnresolvedRelation {
                model,
                field,
                scope,
            } => {
                write!(
                    f,
                    "projection of {model}.{field} for scope `{scope}` failed: \
                     relation is not resolved (call .prefetch() before projecting)"
                )
            }
        }
    }
}

impl std::error::Error for ProjectionError {}

/// Unreachable — `Infallible` has no inhabitants. The impl exists so
/// generated `TryFrom` chains with `?` can coerce the blanket-provided
/// `Infallible` error into `ProjectionError` uniformly.
impl From<Infallible> for ProjectionError {
    fn from(never: Infallible) -> Self {
        match never {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unresolved_relation_display_includes_all_context() {
        let err = ProjectionError::UnresolvedRelation {
            model: "Vehicle",
            field: "owner",
            scope: "public",
        };
        let msg = err.to_string();
        assert!(msg.contains("Vehicle"));
        assert!(msg.contains("owner"));
        assert!(msg.contains("public"));
        assert!(msg.contains(".prefetch()"));
    }

    #[test]
    fn infallible_converts_to_projection_error() {
        fn accepts_from<T: From<::std::convert::Infallible>>() {}
        accepts_from::<ProjectionError>();
    }
}
