//! Core type aliases and re-exports used in `#[model]` struct definitions.
//!
//! Every `#[model]` struct pulls these in via `djogi::prelude::*`, so users
//! never need per-field imports for the framework's canonical types. The
//! aliases (`DateTime`, `Date`) pin the project to the `time` crate — the
//! framework explicitly avoids `chrono` (see CLAUDE.md "Dependencies
//! excluded").
//!
//! The `__*_default` helpers are hidden sentinels used only by the `Default`
//! impl the macro emits for each model. `create()` ignores the framework
//! fields on the input struct, so these sentinel values never reach the
//! database — they exist solely so `..Default::default()` works at call sites.

pub use heeranjid::{HeerId, HeerIdDesc, RanjId, RanjIdDesc, RanjPrecision};

/// `TIMESTAMPTZ` — alias for `time::OffsetDateTime`.
pub type DateTime = time::OffsetDateTime;

/// `DATE` — alias for `time::Date`.
pub type Date = time::Date;

// ---------------------------------------------------------------------------
// Default impls for framework-injected fields.
//
// `#[model]` generates a Default impl for the whole struct. These impls
// provide sentinel values for the framework fields (id, created_at,
// updated_at). The values are irrelevant — create() ignores them.
// ---------------------------------------------------------------------------

/// Sentinel zero value for use in `Default` impls generated by `#[model]`.
///
/// `HeerId::from_i64(0)` is Ok because 0 is non-negative — this is the
/// cheapest always-valid HeerId. The value never reaches the database:
/// `create()` uses `RETURNING id` to replace it with a DB-generated ID.
#[doc(hidden)]
pub fn __heerid_default() -> HeerId {
    HeerId::from_i64(0).expect("HeerId(0) is always valid as a sentinel")
}

/// Sentinel value for `RanjId` `Default` impls.
///
/// `Uuid::nil()` does NOT work here — nil has version=0, and `RanjId::from_uuid`
/// rejects anything except UUIDv8. Instead we construct the minimum valid
/// RanjId via `RanjId::new(0, Microseconds, 0, 0)`, which sets the correct
/// version/variant bits. As with `__heerid_default`, the value never reaches
/// the database — `create()` overwrites it via `RETURNING id`.
#[doc(hidden)]
pub fn __ranjid_default() -> RanjId {
    RanjId::new(0, RanjPrecision::Microseconds, 0, 0)
        .expect("RanjId with all-zero components is always valid as a sentinel")
}

/// Sentinel zero value for `HeerIdDesc` `Default` impls.
///
/// Analogous to [`__heerid_default`]: `HeerIdDesc::from_i64(0)` is always
/// valid (the Desc XOR mask is applied over a non-negative logical
/// component-tuple, not the stored bit pattern) and the value never reaches
/// the database — `create()` overwrites it via `RETURNING id`.
#[doc(hidden)]
pub fn __heerid_desc_default() -> HeerIdDesc {
    HeerIdDesc::new(0, 0, 0).expect("HeerIdDesc(0,0,0) is always valid as a sentinel")
}

/// Sentinel value for `RanjIdDesc` `Default` impls.
///
/// Mirrors [`__ranjid_default`]: minimum valid RanjIdDesc — all-zero logical
/// components at microsecond precision. The value never reaches the
/// database; `create()` overwrites it via `RETURNING id`.
#[doc(hidden)]
pub fn __ranjid_desc_default() -> RanjIdDesc {
    RanjIdDesc::new(0, RanjPrecision::Microseconds, 0, 0)
        .expect("RanjIdDesc with all-zero components is always valid as a sentinel")
}
