//! Visage runtime — error types for generated visage structs.
//!
//! Emits four visage structs per `#[model]` struct
//! (`{Model}Public`, `{Model}SelfView`, `{Model}Admin`, `{Model}Export`) plus
//! conversion impls. This module holds the runtime-side types those
//! conversions depend on:
//!
//! - [`VisageError`] — the fallible-conversion error type, returned by
//!   every `TryFrom<&Model>` impl that nests a relation-form peer visage.
//!   `#[non_exhaustive]` so later phases (e.g. protected-data governance)
//!   can add variants without a breaking change.
//! - `impl From<Infallible> for VisageError` — unreachable glue that lets
//!   generated code propagate `Infallible` with `?` when a peer visage is
//!   scalar-only.
//!
//! No runtime execution happens here — every path is straight-line error
//! construction or formatting.

use std::convert::Infallible;

/// Error returned by a fallible visage conversion (`TryFrom<&Model>`).
///
/// Generated by codegen whenever a visage nests at least one peer visage
/// via a relation field. The only variant today is
/// [`VisageError::UnresolvedRelation`], raised when the caller forgot to
/// `prefetch` / `select_related` the relation before projecting.
///
/// `#[non_exhaustive]` is intentional: protected-data governance and later
/// phases may add variants (e.g. redaction failures, codec errors) without
/// breaking the public API.
#[non_exhaustive]
#[derive(Debug, thiserror::Error)]
pub enum VisageError {
    /// A relation field was projected before the relation was loaded.
    ///
    /// Fix: call `.prefetch(|r| r.<field>())` (or `.select_related(...)` for
    /// SQL-JOIN eager loading) on the queryset before invoking
    /// `TryFrom::try_from(&model)`.
    #[error(
        "visage of {model}.{field} for scope `{scope}` failed: \
         relation is not resolved (call .prefetch() before projecting)"
    )]
    UnresolvedRelation {
        /// Name of the owning model (`struct` ident).
        model: &'static str,
        /// Name of the relation field on the owning model.
        field: &'static str,
        /// Visage scope whose `TryFrom` impl raised this error
        /// (`public` / `self_view` / `admin` / `export`).
        scope: &'static str,
    },
}

/// Unreachable — `Infallible` has no inhabitants. The impl exists so
/// generated `TryFrom` chains with `?` can coerce the blanket-provided
/// `Infallible` error into `VisageError` uniformly.
impl From<Infallible> for VisageError {
    fn from(never: Infallible) -> Self {
        match never {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unresolved_relation_display_includes_all_context() {
        let err = VisageError::UnresolvedRelation {
            model: "Vehicle",
            field: "owner",
            scope: "public",
        };
        let msg = err.to_string();
        assert!(msg.contains("Vehicle"));
        assert!(msg.contains("owner"));
        assert!(msg.contains("public"));
        assert!(msg.contains(".prefetch()"));
    }

    #[test]
    fn infallible_converts_to_visage_error() {
        fn accepts_from<T: From<::std::convert::Infallible>>() {}
        accepts_from::<VisageError>();
    }
}
